- name: Create ansible user
  user:
    name: ansible
    uid: 900

- name: Copy ansibles sudo configuration
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: Replace pi user
  user:
    - username: patrick
      name: Patrick
      groups: ['wheel', 'sudo']
      uid: 1000
      gid: 1000
